version: "3"
services:
  nginx:
    image: nginx
    ports:
        - 80:80
    depends_on:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/500.html:/etc/nginx/conf.d/500.html

  app:
    build: ./sample-app
    # Links deprecated
    # links:
    #   - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      # TODO: Manage Secrets Securely
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/:ro
